// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whevwhzpwhuvqsqiktns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoZXZ3aHpwd2h1dnFzcWlrdG5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMzY1MjIsImV4cCI6MjA1NzYxMjUyMn0.mURbeG017KDk0VIndADKv4mDR4maLzFUnO2cdD4fF8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);